version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "Studio-Nullbyte"
    assignees:
      - "Studio-Nullbyte"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    # Group dependency updates
    groups:
      react:
        patterns:
          - "react*"
          - "@types/react*"
        update-types:
          - "minor"
          - "patch"
      testing:
        patterns:
          - "@testing-library/*"
          - "vitest"
          - "jsdom"
        update-types:
          - "minor"
          - "patch"
      build-tools:
        patterns:
          - "vite*"
          - "@vitejs/*"
          - "typescript"
          - "autoprefixer"
          - "postcss"
          - "tailwindcss"
        update-types:
          - "minor"
          - "patch"
      linting:
        patterns:
          - "eslint*"
          - "@typescript-eslint/*"
          - "prettier"
        update-types:
          - "minor"
          - "patch"
      azure:
        patterns:
          - "@azure/*"
          - "azure-*"
        update-types:
          - "minor"
          - "patch"
    # Ignore specific dependencies that might cause issues
    ignore:
      # Ignore major version updates for core frameworks
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]
      - dependency-name: "vite"
        update-types: ["version-update:semver-major"]
      # Ignore specific packages that might have breaking changes
      - dependency-name: "tailwindcss"
        update-types: ["version-update:semver-major"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "Studio-Nullbyte"
    assignees:
      - "Studio-Nullbyte"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "github-actions"
      - "automated"

  # Enable version updates for Docker (if using containers)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "Studio-Nullbyte"
    assignees:
      - "Studio-Nullbyte"
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "docker"
      - "automated"
